### ISSUE TITLE
Factorio 0.16 compatibility

### ISSUE THREAD

**Issue by SergeyFromHell** [Choumiko/PitchBlack#1]
Please, port this wondeful mod to the 0.16 version of the game!

**Comment by Choumiko** [comment]
Updated to 0.16
I'm gonna upload to the portal as soon as it gets back online.
Should be enough to just change what i changed here: https://github.com/Choumiko/PitchBlack/commit/0952ec598ea97b166452fd9a512a452c3b6893eb#diff-379da8ee275d0393f12cdff8542d368d
