### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by OvermindDL1** [Choumiko/PitchBlack#2]
Quite a pack of mods I added it into, but it causes this error on initial game load:

```
  24.598 Mods to disable:Failed to load mods: __Pitch_Black__/data-updates.lua:80: attempt to perform arithmetic on field 'damage_modifier' (a nil value)
```

Sans this mod then everything loads fine.

Factorio:  0.16.15
PitchBlack:  1.0.0

**Comment by Choumiko** [comment]
That's another mod adding/changing spitters. It should be fixed in the latest version.
I added some debug output to factorio-current.log, if you could upload yours with the latest version of Pitch Black it might help find the mod causing it

**Comment by OvermindDL1** [comment]
Sorry for the delay, current version is not crashing, here's the log from one of the server-goer's current running instances with the current version:  https://cdn.discordapp.com/attachments/320192373437104130/402847597640941568/factorio-current.log
